Support auth message both client side and server side.
vert-x3/vertx-mqtt pull request #248
Opened 2024-06-26 11:05 UTC by qianwj

Motivation:

At the moment of writing, the vertx-mqtt supports all MQTT version 5.0 features except AUTH message which is yet to be implemented. Now I used it to develop my mqtt broker. So, I try to finished this.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2024-06-26 11:31 UTC, vietj commented
can you sign the eclipse contributor agreement @qianwj ?

2024-06-27 13:43 UTC, qianwj commented
> 你能签署 Eclipse 贡献者协议吗 @qianwj ?

2024-06-27 13:44 UTC, qianwj commented
I just signed up.

2024-07-02 11:49 UTC, vietj commented on src/main/java/io/vertx/mqtt/messages/MqttAuthenticationExchangeMessage.java
> +  @GenIgnore
`@GenIgnore(GenIgnore.PERMITED_TYPES)`

2024-07-02 11:51 UTC, vietj commented
The contribution looks great, can you add documentation for this in index.adoc ?

2024-07-05 03:30 UTC, qianwj commented
done. [https://github.com/vert-x3/vertx-mqtt/pull/248/commits/a69174152451cc635f7f6a6f432b1ee448a32353](https://github.com/vert-x3/vertx-mqtt/pull/248/commits/a69174152451cc635f7f6a6f432b1ee448a32353)

2024-07-23 16:35 UTC, qianwj commented
hi @vietj  , I hope you're doing well. It has been almost a month since I submitted my code changes for review. I understand you might be busy, but I wanted to kindly remind you about my pull [https://github.com/vert-x3/vertx-mqtt/pull/248](https://github.com/vert-x3/vertx-mqtt/pull/248) and request your review.

2024-07-24 07:18 UTC, ppatierno requested changes

2024-07-24 07:18 UTC, ppatierno commented on src/main/java/io/vertx/mqtt/MqttClient.java
> +   * Unsubscribe from receiving messages on given list of topic
I think this comment is wrong, coming from a copy/paste, or?

2024-07-24 07:18 UTC, ppatierno commented on src/main/java/io/vertx/mqtt/MqttEndpoint.java
> +   * received by the remote MQTT client
please leave a blank line right after the description

2024-07-24 07:18 UTC, ppatierno commented on src/main/java/examples/VertxMqttServerExamples.java
> +   * Example for authentication exchange
please leave a blank line right after the description

2024-07-24 07:18 UTC, ppatierno commented on src/main/java/io/vertx/mqtt/MqttEndpoint.java
> +   * Sends the AUTH message to the remote MQTT client
please leave a blank line right after the description

2024-07-24 07:18 UTC, ppatierno commented on src/main/java/io/vertx/mqtt/messages/codes/MqttAuthenticateReasonCode.java
> +  ;
should this be just on the previous line?

2024-07-24 07:18 UTC, ppatierno commented on src/test/java/io/vertx/mqtt/test/server/Mqtt5ServerAuthTest.java
> + * MQTT server testing about server publish
it's not testing server publish, but server auth.

2024-08-04 06:26 UTC, qianwj commented
done.

2024-08-04 09:57 UTC, ppatierno approved these changes
LGTM

2024-08-04 09:58 UTC, ppatierno commented
@vietj is there anything on your side here?

2024-10-01 19:14 UTC, merged

2024-10-01 19:14 UTC, vietj commented
thank you @qianwj